### ISSUE TITLE
Bug on load

### ISSUE THREAD

**Issue by danglephd** [thiagodnf/rock-paper-scissor-simulator#1]
Please check your sourcecode, the setting is not work because it's stuck on Init:

![image](https://github.com/thiagodnf/rock-paper-scissor-simulator/assets/30063611/7c12e48a-8c37-4253-a4a3-2758e1ed02e9)

**Comment by thiagodnf** [comment]
Thank you @danglephd for sharing this bug. May I ask you to double check if now it is working?

https://thiagodnf.github.io/rock-paper-scissor-simulator

**Comment by danglephd** [comment]
Hi @thiagodnf , It 's work good for me.

**Comment by thiagodnf** [comment]
Thank you @danglephd
